[tools]
hugo = "extended_0.128.0"

[tasks.build]
description = "Build the site"
run = "hugo --gc"

[tasks.ci]
description = "Run the CI build"
depends = [
	"build"
]

[tasks.serve]
description = "Start the Hugo server"
run = "hugo server --buildDrafts --gc"

[tasks.lint]
description = "Lint the site"
run = "npx prettier --check ."

[tasks.format]
description = "Format the site"
run = "npx prettier --write ."

[tasks.clean]
description = "Clean the Hugo cache"
run = [
	"rm -rf public",
	"rm -rf resources",
	"rm .hugo_build.lock",
]

[tasks.reset]
description = "Runs clean and serve"
depends = [
	"clean",
	"serve"
]
