baseURL = "https://hisaac.net/"
title = "hisaac.net"

archetypeDir = "src/archetypes"
assetDir = "src/assets"
contentDir = "src/content"
dataDir = "src/data"
layoutDir = "src/layouts"
staticDir = "src/static"
themesDir = "src/themes"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[markup]
	[markup.goldmark.renderer]
		unsafe = true

	[markup.goldmark.extensions.typographer]
		disable = true

	[markup.highlight]
		noClasses = false

[params]
	# The description of your website
	description = "Isaac Halvorson's personal weblog"

	# The path to your favicon
	favicon = "favicon.ico"

	# Dates are displayed following the format below. For more information about
	# formatting, see https://gohugo.io/functions/format/
	dateFormat = "Jan 2, 2006"

	# Author metadata. This is mostly used for the RSS feed of your site, but the
	# email is also added to the footer of each post
	[params.author]
		name = "Isaac Halvorson" # Your name as shown in the RSS feed metadata
		email = "hello@hisaac.net" # Added to the footer so readers can reply to posts
