[settings]
activate_aggressive = true
experimental = true

[tools]
hk = "latest"
hugo-extended = "latest"
pkl = "latest"
prettier = "latest"
python = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
yamlfmt = "latest"
yamllint = "latest"
pipx = "latest"

[tasks.bootstrap]
alias = "deps"
run = "hugo mod tidy"

[tasks.upgrade]
run = ["mise upgrade --bump", "mise exec -- hugo mod get -u ./..."]

[tasks.nuke]
depends = ["clean nuke"]

[tasks.ci]
depends = ["bootstrap", "build", "format"]

[tasks.rebuild]
depends = ["clean", "build"]

[tasks.reset]
depends = ["clean", "run"]

[tasks.check]
run = "hk check --all"

[tasks.fix]
run = "hk fix --all"
