[settings]
activate_aggressive = true
experimental = true

[tools]
hk = "latest"
hugo-extended = "latest"
pkl = "latest"
prettier = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
yamllint = "latest"

[hooks]
postinstall = "mise run deps"

[tasks.deps-install]
alias = "deps"
run = "hugo mod tidy"

[tasks.deps-upgrade]
run = ["mise upgrade --bump", "hugo mod get -u ./..."]

[tasks.nuke]
depends = ["clean nuke"]

[tasks.ci]
depends = ["build", "format"]

[tasks.rebuild]
depends = ["clean", "build"]

[tasks.reset]
depends = ["clean", "run"]
