---
title: hisaac.net
name: hisaac.net
author: Isaac Halvorson
email: hello@hisaac.net
description: The personal website of Isaac Halvorson
url: "https://hisaac.net"
twitter_username: hisaac
github_username: hisaac

permalink: /:title/
timezone: America/North_Dakota/Center
strict_front_matter: true
livereload: true

include:
  - _redirects
  - .well-known

keep-files:
  - resume

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: Isaac Halvorson

jekyll_tidy:
  exclude:
    - .well-known/humans.txt
    - .well-known/robots.txt

# https://primer.style/css/getting-started#for-a-jekyll-site
sass:
  # Note the ../ to traverse up
  load_paths:
    - ../build/node_modules/
  # Compress processed CSS to reduce file size
  style: compressed