name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.138.0
      with:
        ruby-version: .tool-versions
        bundler-cache: true

    - name: Build the Site
      run: bundle exec jekyll build --source ./src/
