name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.138.0
      with:
        ruby-version: .tool-versions
        bundler-cache: true

    - name: Build the Site
      run: |
        bundle exec jekyll build \
          --source ./src/ \
          --destination ${{ github.workspace }}/_site

    - name: Deploy the Site to Amazon S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: ${{ github.workspace }}/_site

    - name: Invalidate CloudFront cache
      uses: chetan/invalidate-cloudfront-action@v2.4
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: /*
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
