name: Build

on:
  pull_request:
    types:
    - labeled
    - opened
    - synchronize
    - reopened
    - unlabeled
    - converted_to_draft
    - ready_for_review
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout

    - name: Setup Ruby
      uses: ruby/setup-ruby
      with:
        ruby-version: .tool-versions
        bundler-cache: true

    - name: Build the Site
      run: bundle exec jekyll build
